# required for building jre_lwjgl3glfw with Java 8 while using plugins in app_pojavlauncher that require Java 11
org.gradle.jvmargs=-Xmx2048m
org.gradle.configureondemand=true
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.bundle.language.enableSplit=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
